debug: false
max_incidents: 10
concurrent_tasks: 20
summarizers:
  t5: true
  bart: true
  bert: true
evaluate: true
evaluation_options:
  bleu: true
  rouge: true
  bertscore: true
  readability: true
  bert: true
prompts:
  detailed: "Provide a concise (up to 200 words) academic-style summary of this incident. Include an explanation of the risk factors (‘IdentifiedRisks’) and the rationale for the chosen mitigation (ResolutionDetails). Maintain an objective, formal tone."
duration_tracking: true
incident_workers: 10  # Number of threads for processing incidents within each summarizer